language: swift
osx_image: xcode8.3

before_install:
  - brew install swiftlint

script:
    - swiftlint
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project LazySwift.xcodeproj -scheme LazySwift -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=10.3.1'

after_success:
    - bash <(curl -s https://codecov.io/bash)
