language: swift
osx_image: xcode9

before_install:
  - brew install swiftlint

script:
    - swiftlint
    - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project LazyArray.xcodeproj -scheme LazyArray -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.0'

after_success:
    - bash <(curl -s https://codecov.io/bash)
